apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-storage-secret
  namespace: bold-services
type: Opaque
stringData:
  BOLD_SERVICES_AWS_ACCESS_KEY_ID: ""
  BOLD_SERVICES_AWS_SECRET_ACCESS_KEY: ""
  BOLD_SERVICES_AMAZON_BUCKET_NAME: ""
  BOLD_SERVICES_AWS_REGION: ""
  BOLD_SERVICES_AMAZON_ROOTFOLDER_NAME: ""
  BOLD_SERVICES_STORAGETYPE: "3"
