apiVersion: v1
kind: Secret
metadata:  
  name: azure-blob-storage-secret
  namespace: bold-services
type: Opaque
stringData:
  BOLD_SERVICES_AZUREBLOB_ACCESSKEY: ""
  BOLD_SERVICES_AZUREBLOB_ACCOUNT_NAME: ""
  BOLD_SERVICES_AZUREBLOB_CONTAINER_NAME: ""
  BOLD_SERVICES_AZUREBLOB_CONNECTION_TYPE: ""
  BOLD_SERVICES_AZUREBLOB_STORAGE_URI: ""
  BOLD_SERVICES_STORAGETYPE: "1"