apiVersion: v1
kind: Secret
metadata:  
  name: oci-storage-secret
  namespace: bold-services
type: Opaque
stringData:
  BOLD_SERVICES_OCI_ACCESS_KEY: ""
  BOLD_SERVICES_OCI_BUCKET_NAME: ""
  BOLD_SERVICES_OCI_NAME_SPACE: ""
  BOLD_SERVICES_OCI_REGION: ""
  BOLD_SERVICES_OCI_ROOTFOLDER_NAME: ""
  BOLD_SERVICES_OCI_SECRET_KEY: ""
  BOLD_SERVICES_STORAGETYPE: "4"